name: Go

on:
    release:
        types: [created]

permissions:
    contents: write
    packages: write

jobs:
    release-matrix:
        name: Release Go Binary
        runs-on: ubuntu-latest
        strategy:
            matrix:
                goos: [linux]
                goarch: [amd64]
        steps:
            - uses: actions/checkout@v4
            - uses: wangyoucao577/go-release-action@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  goos: ${{ matrix.goos }}
                  goarch: ${{ matrix.goarch }}
                  project_path: ./
                  compress_assets: OFF
                  asset_name: media-ripper-2-${{ matrix.goos }}-${{ matrix.goarch }}
                  build_command: 'CGO_ENABLED=0 go build'
